name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Adjust to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t admineng/oneblock:latest .
        docker tag admineng/oneblock:latest ${{ secrets.DOCKER_USERNAME }}/oneblock:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/oneblock:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configure gcloud
      run: |
        gcloud config set project tugu-blockchain-dev
        gcloud config set compute/zone asia-southeast2-a

    - name: Deploy to Google Compute Engine
      run: |
        gcloud compute instances create-with-container blockchain-node1-production \
          --container-image=${{ secrets.DOCKER_USERNAME }}/oneblock:latest \
          --container-arg="--license-key=${{ secrets.DOCKER_LICENSE_KEY }}"
        # Adjust this command if using Kubernetes or another deployment method

