name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Adjust to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t admineng/oneblock:latest .
        docker tag admineng/oneblock:latest ${{ secrets.DOCKER_USERNAME }}/oneblock:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/oneblock:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: SSH into the instance and deploy container
      run: |
        gcloud compute ssh blockchain-node1-production --zone=asia-southeast2-a --command="
        sudo docker pull ${{ secrets.DOCKER_USERNAME }}/oneblock:latest &&
        sudo docker stop oneblock || true &&
        sudo docker rm oneblock || true &&
        sudo docker run -d --name oneblock \
          -p 8545:8545 -p 30303:30303 \
          ${{ secrets.DOCKER_USERNAME }}/oneblock:latest --license-key=${{ secrets.DOCKER_LICENSE_KEY }}"

