name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Adjust to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Initialize and update submodules
      run: git submodule update --init --recursive

    - name: List root directory contents
      run: ls -la

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        # Build the Docker image using the updated Dockerfile
        docker build -t ${{ secrets.DOCKER_USERNAME }}/oneblock:latest -f Dockerfile .
        docker push ${{ secrets.DOCKER_USERNAME }}/oneblock:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

    - name: SSH into the instance, prepare the environment, install Docker, and deploy container
      run: |
        gcloud compute ssh blockchain-node1-production --zone=asia-southeast2-a --command="
        # Update package lists
        sudo apt-get update &&
        
        # Remove conflicting packages
        sudo apt-get remove --purge -y containerd containerd.io &&
        
        # Clean up package lists
        sudo apt-get autoremove -y &&
        sudo apt-get clean &&
        sudo apt-get autoclean &&
        
        # Install Docker from the official repository
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common &&
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add - &&
        sudo add-apt-repository \"deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable\" &&
        sudo apt-get update &&
        sudo apt-get install -y docker-ce docker-ce-cli containerd.io &&
        
        # Check if the directory exists and create it if necessary
        if [ ! -d /root/.ethereum ]; then
          sudo mkdir -p /root/.ethereum &&
          sudo chown -R $(whoami):$(whoami) /root/.ethereum
        fi &&
        
        # Initialize Geth with the genesis block if not already initialized
        if [ ! -f /root/.ethereum/geth/chaindata/LOCK ]; then
          sudo docker run --rm -v /root/.ethereum:/root/.ethereum -v $(pwd)/genesis.json:/genesis.json ${{ secrets.DOCKER_USERNAME }}/oneblock:latest init /genesis.json
        fi &&
        
        # Stop any running container and remove it
        sudo docker stop oneblock || true &&
        sudo docker rm oneblock || true &&
        
        # Run the Docker container with the correct consensus flag
        sudo docker run -d --name oneblock \
          -p 8545:8545 -p 30303:30303 \
          -e NETWORK_ID=10 \
          -e HTTP_PORT=8545 \
          -e PORT=30303 \
          -e RAFT=true \
          ${{ secrets.DOCKER_USERNAME }}/oneblock:latest"

