name: CI/CD Pipeline

on:
  push:
    branches:
      - master # Adjust to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      run: |
        docker build -t admineng/oneblock:latest .
        docker tag admineng/oneblock:latest ${{ secrets.DOCKER_USERNAME }}/oneblock:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/oneblock:latest

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v0.6.0
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        echo "Host *" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

    - name: SSH into the instance, prepare the environment, install geth, and deploy container
      run: |
        gcloud compute ssh blockchain-node1-production --zone=asia-southeast2-a --command="
        # Update package lists
        sudo apt-get update &&
        
        # Install build-essential and golang-go
        sudo apt-get install -y build-essential golang-go &&
        
        # Install Geth (Go Ethereum)
        sudo add-apt-repository -y ppa:ethereum/ethereum &&
        sudo apt-get update &&
        sudo apt-get install -y geth &&
        
        # Check if the directory exists
        if [ ! -d /var/www/oneblockv1 ]; then
          # Create the directory if it doesn't exist
          sudo mkdir -p /var/www/oneblockv1 &&
          # Set proper permissions
          sudo chown -R $(whoami):$(whoami) /var/www/oneblockv1
        fi &&
        
        # Navigate to the project directory
        cd /var/www/oneblockv1 &&
        
        # Compile the blockchain node
        make geth &&
        
        # Verify the build
        ls build/bin/ &&
        
        # Initialize the blockchain with the genesis file
        build/bin/geth --datadir /var/www/oneblockv1/datadir init /var/www/oneblockv1/genesis.json &&
        
        # Move the binary to the standard bin directory
        sudo mv build/bin/geth /usr/local/bin/ &&
        
        # Initialize again using the moved binary
        geth --datadir /var/www/oneblockv1/datadir init /var/www/oneblockv1/genesis.json &&
        
        # Stop any running container and remove it
        sudo docker stop oneblock || true &&
        sudo docker rm oneblock || true &&
        
        # Run the Docker container
        sudo docker run -d --name oneblock \
          -p 8545:8545 -p 30303:30303 \
          ${{ secrets.DOCKER_USERNAME }}/oneblock:latest --license-key=${{ secrets.DOCKER_LICENSE_KEY }} &&
        
        # Start the blockchain node in the background
        nohup geth --datadir /var/www/oneblockv1/datadir --networkid 10 --port 30303 --http --http.api admin,eth,net,web3 --http.addr 0.0.0.0 --http.port 8545 > geth.log 2>&1 &"
